server:
    baseurl: http://localhost:5000
    port: 5000

apiserver:
    hostname: ca.adito.dev
    port: 8080
    tls: false

csr_defaults:
    country: DE
    state: Bavaria
    locality: Geisenhausen
    organization: ADITO Software GmbH
